<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="0.081" timestamp="2024-12-07T14:36:41.574042+01:00" hostname="DELL-JSA"><testcase classname="" name="test.unit.calc_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\julia\Documents\GitHub\helloworld\test\unit\calc_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test\unit\calc_test.py:4: in &lt;module&gt;
    from app.calc import Calculator
E   ModuleNotFoundError: No module named 'app'</error></testcase><testcase classname="" name="test.unit.util_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\julia\Documents\GitHub\helloworld\test\unit\util_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test\unit\util_test.py:4: in &lt;module&gt;
    from app import util
E   ModuleNotFoundError: No module named 'app'</error></testcase></testsuite></testsuites>